In [1]:
import pandas as pd
import numpy as np

In [7]:
#It will prompt you to select a file.
from google.colab import files
uploaded = files.upload()

Saving mobiles.csv to mobiles.csv

In [8]:
#to import it into a dataframe
import io
df = pd.read_csv(io.BytesIO(uploaded['mobiles.csv']))

In [ ]:
df.describe()
#The describe() method is used for calculating some statistical data like 
#percentile, mean and std of the numerical values of the Series or DataFrame.

        Unnamed: 0       stars
count  1148.000000  922.000000
mean    573.500000    4.185575
std     331.543361    0.235729
min       0.000000    3.300000
25%     286.750000    4.100000
50%     573.500000    4.200000
75%     860.250000    4.300000
max    1147.000000    4.700000

In [ ]:
# returns the number of elements in the DataFrame. 
#The number of elements is the number of rows * the number of columns
df.size

13776

In [ ]:
#The shape is the number of rows and columns of the DataFrame
df.shape

(1148, 12)

In [ ]:
#Replace all values in the DataFrame with True & False
#True- null
#False- not null
df.isnull()

#True- not null
#false- null
#df.notnull()

,Unnamed: 0,names,images_links,stars,rating&reviews,price_details,memory,camara_info,display,battery,processor,warranty
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1143,False,True,False,True,True,False,True,True,True,True,True,True
1144,False,True,False,True,True,False,True,True,True,True,True,True
1145,False,True,False,True,True,False,True,True,True,True,True,True
1146,False,True,False,True,True,False,True,True,True,True,True,True
1147,False,True,False,True,True,False,True,True,True,True,True,True

In [ ]:
#prints information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1148 entries, 0 to 1147
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1148 non-null   int64
 1   names           943 non-null    object
 2   images_links    1143 non-null   object
 3   stars           922 non-null    float64
 4   rating&reviews  922 non-null    object
 5   price_details   1143 non-null   object
 6   memory          943 non-null    object
 7   camara_info     943 non-null    object
 8   display         943 non-null    object
 9   battery         943 non-null    object
 10  processor       900 non-null    object
 11  warranty        616 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 107.8+ KB

In [ ]:
#returns the first 5 rows if a number is not specified.
df.head(1)
#head(n)

,Unnamed: 0,names,images_links,stars,rating&reviews,price_details,memory,camara_info,display,battery,processor,warranty
0,0,"SAMSUNG Galaxy F13 (Waterfall Blue, 64 GB)",https://rukminim1.flixcart.com/image/312/312/x...,4.4,"1,20,759 Ratings & 7,003 Reviews","₹9,699\n₹14,99935% off",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 5MP + 2MP | 8MP Front Camera,16.76 cm (6.6 inch) Full HD+ Display,6000 mAh Lithium Ion Battery,Exynos 850 Processor,1 Year Warranty Provided By the Manufacturer f...

In [ ]:
#same like head just it return last specified elements
df.tail(2)

,Unnamed: 0,names,images_links,stars,rating&reviews,price_details,memory,camara_info,display,battery,processor,warranty
1146,1146,NaN,https://rukminim1.flixcart.com/image/300/300/j...,NaN,NaN,"₹1,14528% off",NaN,NaN,NaN,NaN,NaN,NaN
1147,1147,NaN,https://rukminim1.flixcart.com/image/300/300/x...,NaN,NaN,"₹1,48525% off",NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
#Deal with missing data, Drop data Replace data
#replced by sum

In [9]:
df.isnull().sum()

Unnamed: 0          0
names             205
images_links        5
stars             226
rating&reviews    226
price_details       5
memory            205
camara_info       205
display           205
battery           205
processor         248
warranty          532
dtype: int64

In [12]:
df.min()

<ipython-input-12-c3612c624a3f>:1: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.min()

Unnamed: 0    0.0
stars         3.3
dtype: float64

In [13]:
df.max()

<ipython-input-13-4c1ddf8920ff>:1: FutureWarning: The default value of numeric_only in DataFrame.max is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.max()

Unnamed: 0    1147.0
stars            4.7
dtype: float64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1148 entries, 0 to 1147
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1148 non-null   int64
 1   names           943 non-null    object
 2   images_links    1143 non-null   object
 3   stars           922 non-null    float64
 4   rating&reviews  922 non-null    object
 5   price_details   1143 non-null   object
 6   memory          943 non-null    object
 7   camara_info     943 non-null    object
 8   display         943 non-null    object
 9   battery         943 non-null    object
 10  processor       900 non-null    object
 11  warranty        616 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 107.8+ KB

In [16]:
#calculate the mean vaule for "stars" column
avg_stars = df['stars'].astype(float).mean(axis=0)
print(avg_stars)

4.185574837310195

In [19]:
# replace NaN by mean value in "stroke" column
rep_values = df['stars'].replace(np.nan, avg_stars,inplace=True)
print(rep_values)

None

In [20]:
#list of columns
df.columns

Index(['Unnamed: 0', 'names', 'images_links', 'stars', 'rating&reviews',
       'price_details', 'memory', 'camara_info', 'display', 'battery',
       'processor', 'warranty'],
      dtype='object')

In [21]:
df['stars'].value_counts()

4.185575    226
4.300000    210
4.100000    152
4.200000    142
4.400000    111
4.000000    105
3.700000     47
4.500000     46
3.900000     29
4.700000     27
3.800000     26
4.600000     13
3.600000      5
3.300000      3
3.400000      3
3.500000      3
Name: stars, dtype: int64

In [24]:
#datatypes of the columns
df.dtypes

Unnamed: 0          int64
names              object
images_links       object
stars             float64
rating&reviews     object
price_details      object
memory             object
camara_info        object
display            object
battery            object
processor          object
warranty           object
dtype: object

In [26]:
#particular columns
df.stars.dtypes

dtype('float64')

In [30]:
#select particular datapyes columns(exclude - to reject)
df.select_dtypes(include="float")

         stars
0     4.400000
1     4.400000
2     4.100000
3     4.400000
4     4.400000
...        ...
1143  4.185575
1144  4.185575
1145  4.185575
1146  4.185575
1147  4.185575

[1148 rows x 1 columns]

In [31]:
#Changing datatype of columns
var = {'stars' : int}
df=df.astype(var)
df.dtypes

Unnamed: 0         int64
names             object
images_links      object
stars              int64
rating&reviews    object
price_details     object
memory            object
camara_info       object
display           object
battery           object
processor         object
warranty          object
dtype: object

In [36]:
#Turn categorical variables into quantitative variables in Python.
#df['Education'].replace(['Under-Graduate', 'Diploma '],[0, 1], inplace=True)

Preprocessing is the process of doing a pre-analysis of data, in order to transform them into a standard and normalized format. Preprocessing involves the following aspects:

missing values
data formatting
data normalization
data standardization
data binning

Standardization is the process of transforming data into a common format which allows the researcher to make the meaningful comparison.

**Data Normalization**

to transform the numerical features of a dataset to a standardized scale. The goal is to ensure that all features have the same range 

1. Min-Max Normalization (Rescaling):

In this method, the values of the dataset are scaled to a fixed range, usually between 0 and 1. 

X_normalized = (X - X_min) / (X_max - X_min)

2. Z-Score Normalization (Standardization):

Z-score normalization transforms the data to have a mean of 0 and a standard deviation of 1

X_normalized = (X - X_mean) / X_std

Data formatting is the process of transforming data into a common format, which helps users to perform comparisons. An example of not formatted data is the following: the same entity is referred in the same column with different values,